# Generated by Django 3.1.2 on 2020-11-04 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shelf', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookauthor',
            name='died',
            field=models.DateField(blank=True, null=True),
        ),
    ]
